name: Ahamed Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: '58 13 * * *'

jobs:
  update-readme:
    name: ahamed's README
    runs-on: ubuntu-latest
    steps:
      - uses: ahamed/ahamed@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
